language: go

go:
  - 1.9.2

addons:
  ssh_known_hosts: jhausotter.com

before_install:
  - openssl aes-256-cbc -K $encrypted_285ce119f0f4_key -iv $encrypted_285ce119f0f4_iv
    -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - mv deploy-key ~/.ssh/id_rsa

install:
  - go get -v github.com/spf13/hugo

script:
  - hugo -d public --disableKinds=taxonomy,taxonomyTerm

after_success:
  - bash ./deploy.sh
